### ISSUE TITLE
Remove setuptools_scm from install_requires in setup.py

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/tables_io#27]
The install doesn't require `setuptools_scm`, this is already pulled in when needed via [setup_requires](https://github.com/LSSTDESC/tables_io/blob/19dd7f6511dd2dac853c7b04dd4a30f752353301/setup.py#L10)
Related to https://github.com/LSSTDESC/qp/issues/75

**Comment by eacharles** [comment]
Done with #28
